//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public int IDEVENTS { get; set; }
        public string TENEVENT { get; set; }
        public Nullable<System.DateTime> THOIGIANEV { get; set; }
        public int IDUSER { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
